export const GENDER_OPTIONS = [
  "female",
  "male",
  "non-binary",
  "prefer not to say",
] as const;

export const YEARS_OF_EXPERIENCE_OPTIONS = [
  { value: "0", label: "Less than 1 year" },
  { value: "2", label: "1-2 years" },
  { value: "5", label: "3-5 years" },
  { value: "10", label: "6-10 years" },
  { value: "12", label: "10+ years" },
] as const;

export const INDUSTRY_OPTIONS = [
  "Technology",
  "Finance",
  "Healthcare",
  "Education",
  "Retail",
  "Manufacturing",
  "Logistics",
  "Media & Entertainment",
  "Telecommunications",
  "Energy & Utilities",
  "Construction",
  "Real Estate",
  "Hospitality",
  "Agriculture",
  "Government",
  "Nonprofit",
] as const;

export const COMPANY_SIZE_OPTIONS = [
  { value: "1-10", label: "1-10 employees" },
  { value: "11-50", label: "11-50 employees" },
  { value: "51-200", label: "51-200 employees" },
  { value: "201-500", label: "201-500 employees" },
  { value: "500+", label: "500+ employees" },
] as const;

export const JOB_CATEGORIES = [
  "Engineering",
  "Design",
  "Data",
  "Product",
  "Sales",
  "Marketing",
  "Customer Support",
  "Finance",
  "HR",
] as const;

export const JOB_EXPERIENCE_LEVELS = [
  "Entry-level",
  "Mid-level",
  "Senior",
  "Lead",
] as const;

export const POST_CATEGORIES = [
  "Blog",
  "Job search guide",
  "Hiring guides",
  "Career advice",
  "Interview tips",
  "Company news",
  "Market Report",
] as const;

export const POST_STATUSES = [
  { value: "draft", label: "Draft" },
  { value: "published", label: "Published" },
  { value: "archived", label: "Archived" },
] as const;

export const OTHER_OPTION = "__other__";

export const PROFESSIONAL_TITLES = [
  "Software Engineer",
  "Senior Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Developer",
  "Mobile Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "Product Designer",
  "UI/UX Designer",
  "Graphic Designer",
  "Product Manager",
  "Project Manager",
  "Scrum Master",
  "QA Engineer",
  "Technical Writer",
  "Sales Manager",
  "Accountant",
  "Financial Analyst",
  "Marketing Specialist",
  "Content Writer",
  "Customer Support Specialist",
  "Human Resources Manager",
  "Recruiter",
  "Administrative Assistant",
  "Executive Assistant",
  "Business Analyst",
  "Operations Manager",
] as const;

export const SKILL_OPTIONS = [
  "TypeScript",
  "JavaScript",
  "Node.js",
  "React",
  "React Native",
  "Next.js",
  "Vue.js",
  "Angular",
  "Python",
  "Django",
  "Flask",
  "Java",
  "Spring",
  "Go",
  "Rust",
  "C#",
  ".NET",
  "PHP",
  "Laravel",
  "Ruby",
  "Ruby on Rails",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "GraphQL",
  "REST APIs",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "GCP",
  "Terraform",
  "CI/CD",
  "Git",
  "Linux",
  "Figma",
  "Adobe Photoshop",
  "UI/UX Design",
  "Tailwind CSS",
  "Sass",
  "HTML",
  "CSS",
  "Data Analysis",
  "Excel",
  "Power BI",
  "Tableau",
  "Machine Learning",
  "TensorFlow",
  "PyTorch",
  "Agile",
  "Scrum",
  "Project Management",
  "Communication",
  "Leadership",
  "Problem Solving",
  "Copywriting",
  "SEO",
  "Digital Marketing",
  "Social Media",
  "Customer Service",
  "Sales",
  "Bookkeeping",
  "Payroll",
  "Recruiting",
] as const;

export const COUNTRIES = [
  "Nigeria",
  "Kenya",
  "Ghana",
  "South Africa",
  "Uganda",
  "Tanzania",
  "Rwanda",
  "Ethiopia",
  "Egypt",
  "Morocco",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Netherlands",
  "Spain",
  "Portugal",
  "India",
  "United Arab Emirates",
  "Saudi Arabia",
  "Brazil",
  "Mexico",
] as const;

export const COUNTRY_DIAL_CODES: Record<string, string> = {
  Nigeria: "+234",
  Kenya: "+254",
  Ghana: "+233",
  "South Africa": "+27",
  Uganda: "+256",
  Tanzania: "+255",
  Rwanda: "+250",
  Ethiopia: "+251",
  Egypt: "+20",
  Morocco: "+212",
  "United States": "+1",
  "United Kingdom": "+44",
  Canada: "+1",
  Australia: "+61",
  Germany: "+49",
  France: "+33",
  Netherlands: "+31",
  Spain: "+34",
  Portugal: "+351",
  India: "+91",
  "United Arab Emirates": "+971",
  "Saudi Arabia": "+966",
  Brazil: "+55",
  Mexico: "+52",
};

export const COUNTRY_STATES: Record<string, string[]> = {
  Nigeria: [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa",
    "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti",
    "Enugu", "FCT (Abuja)", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano",
    "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger",
    "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto",
    "Taraba", "Yobe", "Zamfara",
  ],
  Ghana: [
    "Ahafo", "Ashanti", "Bono", "Bono East", "Central", "Eastern",
    "Greater Accra", "North East", "Northern", "Oti", "Savannah",
    "Upper East", "Upper West", "Volta", "Western", "Western North",
  ],
  Kenya: [
    "Bomet", "Embu", "Garissa", "Kakamega", "Kajiado", "Kiambu",
    "Kilifi", "Kisii", "Kisumu", "Machakos", "Meru", "Mombasa",
    "Nairobi", "Nakuru", "Nandi", "Narok", "Nyandarua", "Nyeri",
    "Trans Nzoia", "Turkana", "Uasin Gishu", "Vihiga",
  ],
  "South Africa": [
    "Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal",
    "Limpopo", "Mpumalanga", "Northern Cape", "North West",
    "Western Cape",
  ],
  "United States": [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas",
    "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
    "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana",
    "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico",
    "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma",
    "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
    "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming",
  ],
  "United Kingdom": [
    "England", "Scotland", "Wales", "Northern Ireland",
  ],
  Canada: [
    "Alberta", "British Columbia", "Manitoba", "New Brunswick",
    "Newfoundland and Labrador", "Nova Scotia", "Ontario",
    "Prince Edward Island", "Quebec", "Saskatchewan",
    "Northwest Territories", "Nunavut", "Yukon",
  ],
  Australia: [
    "New South Wales", "Queensland", "South Australia", "Tasmania",
    "Victoria", "Western Australia", "Australian Capital Territory",
    "Northern Territory",
  ],
  India: [
    "Andhra Pradesh", "Assam", "Bihar", "Delhi", "Gujarat",
    "Haryana", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra",
    "Odisha", "Punjab", "Rajasthan", "Tamil Nadu", "Telangana",
    "Uttar Pradesh", "West Bengal",
  ],
};
